### ISSUE TITLE
Abla to skip saving cache on condition

### ISSUE THREAD

**Issue by xepozz** [satackey/action-docker-layer-caching#130]
It will be useful when you don't want to lose time to save cache.

For example, I want to skip saving cache when previous action was failed.
I can specify `if:` condition as `success()` that means that cache should be saved when previous action was successful.

**Comment by tkrugg** [comment]
This is  possible via `skip-save`.
```yml 
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          skip-save: true

```
