### ISSUE TITLE
Cannot set concurrency

### ISSUE THREAD

**Issue by Bilge** [satackey/action-docker-layer-caching#208]
**Describe the bug**
According to `action.yml`, we can set the concurrency. However, setting this parameter appears to have no effect.

https://github.com/satackey/action-docker-layer-caching/blob/cc3f3828e75cbb45f0cf5139b95329c88480aa97/action.yml#L17-L20

**To Reproduce**
```yml
      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          concurrency: 2
```

**Expected behavior**
`concurrency: 2` should appear in the build output.

**Debug logs**
>Run satackey/action-docker-layer-caching@v0.0.11
  with:
    key: docker-layer-caching-CI-{hash}
    restore-keys: docker-layer-caching-CI-
    concurrency: 4
    skip-save: false

**Runner Environment (please complete the following information):**
 - OS: ubuntu-latest
 - Action version: v0.0.11
