### ISSUE TITLE
Rinning with the caching Slower then without a cache

### ISSUE THREAD

**Issue by avifatal** [satackey/action-docker-layer-caching#247]
Hi, 
The image bellow shows that this plugin makes the build really slower. When I run without the plugin, I get better results.
Im sure the problem is on my side, what am I doing wrong?
Thanks

![image](https://user-images.githubusercontent.com/12430740/156205296-431f7899-e3e1-4b8f-8d13-7efc16581f51.png)

This is the code:
```yml
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11

        continue-on-error: true
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build Docker Image
        run: DOCKER_BUILDKIT=1 docker build -t ${{ inputs.APP_NAME }}/${{ inputs.BRANCH_NAME }} -f ./infra/build/${{ inputs.APP_NAME }}/Dockerfile .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker tag ${{ inputs.APP_NAME }}/${{ inputs.BRANCH_NAME }} gcr.io/${{ secrets.PROJECT_ID }}/${{ inputs.APP_NAME }}/${{ inputs.BRANCH_NAME }}
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ inputs.APP_NAME }}/${{ inputs.BRANCH_NAME }}

```
